src copy/objects/Transaction__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Signed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payment pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submission pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DeclinedSig</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Signatures</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>SUB{0000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src copy/classes/DocusignTecipientTriggerStatusHandler.cls
public class DocusignTecipientTriggerStatusHandler {
/*
	public static void beforeUpdate(List<dsfs__DocuSign_Recipient_Status__c> recipientList){
        
        Set<Id> txIds = new Set<Id>();
        Set<Id> dSignStatus = new Set<Id>();
        List<Transaction__c> transactionsforStatus = new List<Transaction__c>();
        // note this needs to be more dynamic 
    
        for(dsfs__DocuSign_Recipient_Status__c dssRecipStatus : recipientList){
            if(dssRecipStatus.dsfs__Envelope_Status__c == AppConstants.DOCUSIGN_STATUS_COMPLETED)
              {  txIds.add(dss.Transaction__c);}
             else if (dss.dsfs__Envelope_Status__c == AppConstants.DOCUSIGN_STATUS_REJECTED)
             { rejectedtxIds.add(dss.Transaction__c);}
        }

        //Update Transactions on DRAFTSTATUS
        for(Transaction__c tx : [Select Id, Status__c from Transaction__c where Id IN :txIds]) {
            if(tx.Status__c != AppConstants.REQUEST_STATUS_SIGNED){
                tx.Status__c = AppConstants.REQUEST_STATUS_SIGNED;
                transactionToUpdate.add(tx);
            } 
        }

         //   TODO: Make more dynamic to handle all of the possible STATUSES
        // update rejected statuses on the Transaction object
       for(Transaction__c rejectedtransactions : [Select Id, Status__c from Transaction__c where Id IN :rejectedtxIds]) {
            //if(rejectedtransactions.Status__c == AppConstants.REQUEST_STATUS_DRAFT){
                rejectedtransactions.Status__c = AppConstants.DOCUSIGN_STATUS_DECLINED_SIG; //AppConstants.DOCUSIGN_STATUS_REJECTED;
                transactionToUpdate.add(rejectedtransactions);
            //} 
        }

        
         
        //Update Transactions
        if(!transactionToUpdate.isEmpty())
            update transactionToUpdate;

    }
    */
}