src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CompanyNumber__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Company Number</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/objects/Shares__c.object
<CustomObject>
    <description>Share Capital SH19 Dependency</description>
    <fields>
        <fullName>Class_of_Shares__c</fullName>
        <label>Class of Shares</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SHARETYPE__c</fullName>
        <label>SHARETYPE</label>
        <length>255</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transaction__c</fullName>
        <label>Transaction</label>
        <referenceTo>Transaction__c</referenceTo>
        <relationshipLabel>Shares</relationshipLabel>
        <relationshipName>Shares</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Share</label>
    <nameField>
        <label>Shares Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shares</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Transaction__c.object
<CustomObject>
    <fields>
        <fullName>CompanyNumber__c</fullName>
        <label>Company Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Transaction (Company)</relationshipLabel>
        <relationshipName>Transaction_Company</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Form_Name__c</fullName>
        <label>Form Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Valid_Step_Ids__c</fullName>
        <description>Pipe delimited list of Step Ids up to the current and next Step only.</description>
        <inlineHelpText>Pipe delimited list of Step Ids up to the current and next Step only.</inlineHelpText>
        <label>Valid Step Ids</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>finishedAddingShares__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Boolean to set once Shares are finished to bypass the Adding Shares Table and call the next Step</description>
        <label>finishedAddingShares</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>finishedAttachments__c</fullName>
        <defaultValue>false</defaultValue>
        <label>finishedAttachments</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>finishedPart1__c</fullName>
        <defaultValue>false</defaultValue>
        <label>finishedPart1</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>selectShareType__c</fullName>
        <label>selectShareType</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>SUB{0000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Transaction_Type__mdt.object
<CustomObject>
    <label>Transaction Type</label>
    <pluralLabel>Transaction Type</pluralLabel>
</CustomObject>

src/objects/Transaction_Type_Step__mdt.object
<CustomObject>
    <label>Transaction Type Step</label>
    <pluralLabel>Transaction Type Steps</pluralLabel>
</CustomObject>

src/classes/SCapitalControllerTest2.cls
@IsTest
public with sharing class SCapitalControllerTest2 {
	public SCapitalControllerTest2() {
		test_method_one();
		test_method_two();
		test_method_three();
	}

	@isTest static void test_method_one() {
		// go forward
		CompaniesHouseTestData testData = CompaniesHouseTestData.getInstance();

		Transaction_Type__mdt testForm = CompaniesHouseTestData.getInstance().testForm;

		Transaction_Type_Step__mdt testStep1 = CompaniesHouseTestData.getInstance().testStep1;
		Account testPresenter = CompaniesHouseTestData.getInstance().presenterAccount;

		Account testCompany = CompaniesHouseTestData.getInstance().companyAccount;


		// needs mock web callout information here for initialize step test
		insert testPresenter;

		insert testCompany;

		Transaction__c transac = testData.tx;

		transac.Company__c = testCompany.Id;
		transac.Valid_Step_Ids__c = testStep1.Id;
		transac.CompanyNumber__c = '05448736';
		transac.finishedAttachments__c = false;
		transac.finishedAddingShares__c = false;
		transac.finishedPart1__c = false;
		transac.selectShareType__c = 'testclass';
		transac.Form_Name__c = 'SH19';
		insert transac;

		Shares__c testShare = new Shares__c();
		testshare.transaction__c = transac.Id;
		testshare.shareType__c = 'STATEMENTOFCAPITAL';
		testshare.Class_of_Shares__c = 'testclass';
		insert testShare;

		PageReference scapital2TestPage = Page.SCapital2;
		scapital2TestPage.getParameters().put('c', SecurityManager.encryptText(transac.Id + AppConstants.ID_DELIM_CHAR + testStep1.Id + AppConstants.ID_DELIM_CHAR + String.valueOf(DateTime.now().getTime())));
		Test.setCurrentPage(scapital2TestPage);

		scapitalcontroller2 scap2controller = new scapitalcontroller2();
		scap2controller.addsameShare();

		scap2controller.previousAction();


		scap2controller.nextAction();
		scap2controller.AddtocurrentShare();
		scap2controller.checkstatus();






		scap2controller.nextAction();

	}

	@isTest static void test_method_two() {
		// go forward
		CompaniesHouseTestData testData = CompaniesHouseTestData.getInstance();

		Transaction_Type__mdt testForm = CompaniesHouseTestData.getInstance().testForm;

		Transaction_Type_Step__mdt testStep1 = CompaniesHouseTestData.getInstance().testStep1;
		Account testPresenter = CompaniesHouseTestData.getInstance().presenterAccount;

		Account testCompany = CompaniesHouseTestData.getInstance().companyAccount;


		// needs mock web callout information here for initialize step test
		insert testPresenter;

		insert testCompany;

		Transaction__c transac = testData.tx;

		transac.Company__c = testCompany.Id;
		transac.Valid_Step_Ids__c = testStep1.Id;
		transac.CompanyNumber__c = '05448736';
		transac.finishedAttachments__c = false;
		transac.finishedAddingShares__c = true;
		transac.finishedPart1__c = false;
		transac.selectShareType__c = 'testclass';
		//transac.Form_Name__c = 'SH19';
		insert transac;

		Shares__c testShare = new Shares__c();
		testshare.transaction__c = transac.Id;
		testshare.shareType__c = 'STATEMENTOFCAPITAL';
		testshare.Class_of_Shares__c = 'testclass';
		insert testShare;

		PageReference scapital2TestPage = Page.SCapital2;
		scapital2TestPage.getParameters().put('c', SecurityManager.encryptText(transac.Id + AppConstants.ID_DELIM_CHAR + testStep1.Id + AppConstants.ID_DELIM_CHAR + String.valueOf(DateTime.now().getTime())));
		Test.setCurrentPage(scapital2TestPage);

		scapitalcontroller2 scap2controller = new scapitalcontroller2();
		scap2controller.checkstatus();
		scap2controller.addsameShare();
		scap2controller.getcurrencies();
		scap2controller.previousAction();
		scap2controller.grabAggUnpaidNon0Value();
		scap2controller.grabAggUnpaid();
		scap2controller.grabAggNomValue ();
		scap2controller.grabnumberOfShares ();
		scap2controller.grabCurrencyType();
		scap2controller.showOtherAgg();
		scap2controller.showCurrencyOther();
		scap2controller.nextAction();
		scap2controller.AddtocurrentShare();
		scap2controller.addnewShares();
		scap2controller.currencyType = 'testcurrencytype';
		scap2controller.addnewShares();
		scap2controller.numberofshares = 100;
		scap2controller.addnewShares();
		scap2controller.nominalvalue = 100;
		scap2controller.addnewShares();
		scap2controller.aggUnpaid = 1;
		scap2controller.addnewShares();
		scap2controller.aggUnpaid = 0;
		scap2controller.addnewShares();
		scap2controller.shareClassType = '';
		scap2controller.addnewShares();
		scap2controller.shareClassType = 'testshareclasstype';
		scap2controller.addnewShares();
		scap2controller.grabAggUnpaid();
		scap2controller.aggHidden = '';
		scap2controller.aggHidden = 'test';
		scap2controller.hasPageErrors = true;
		scap2controller.hasPageErrors = false;
		scap2controller.nextAction();
	}


	@isTest static void test_method_three() {
		// go forward
		CompaniesHouseTestData testData = CompaniesHouseTestData.getInstance();

		Transaction_Type__mdt testForm = CompaniesHouseTestData.getInstance().testForm;

		Transaction_Type_Step__mdt testStep1 = CompaniesHouseTestData.getInstance().testStep1;
		Account testPresenter = CompaniesHouseTestData.getInstance().presenterAccount;

		Account testCompany = CompaniesHouseTestData.getInstance().companyAccount;


		// needs mock web callout information here for initialize step test
		insert testPresenter;

		insert testCompany;

		Transaction__c transac = testData.tx;

		transac.Company__c = testCompany.Id;
		transac.Valid_Step_Ids__c = testStep1.Id;
		transac.CompanyNumber__c = '05448736';
		transac.finishedAttachments__c = false;
		transac.finishedAddingShares__c = true;
		transac.finishedPart1__c = false;
		transac.selectShareType__c = 'testclass';
		insert transac;

		PageReference scapital2TestPage = Page.SCapital2;
		scapital2TestPage.getParameters().put('c', SecurityManager.encryptText(transac.Id + AppConstants.ID_DELIM_CHAR + testStep1.Id + AppConstants.ID_DELIM_CHAR + String.valueOf(DateTime.now().getTime())));
		Test.setCurrentPage(scapital2TestPage);

		scapitalcontroller2 scap2controller = new scapitalcontroller2();
		scap2controller.checkstatus();
		scap2controller.addsameShare();

		scap2controller.previousAction();


		scap2controller.nextAction();
		scap2controller.AddtocurrentShare();

		scap2controller.hasPageErrors = true;
		scap2controller.hasPageErrors = false;





		scap2controller.nextAction();

	}
}