src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CompanyNumber__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Company Number</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/objects/Company_Authorisation__c.object
<CustomObject>
    <fields>
        <fullName>Company_Access_Token__c</fullName>
        <label>Company Access Token</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company_Number__c</fullName>
        <label>Company Number</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Nonce__c</fullName>
        <label>Nonce</label>
        <length>16</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <description>Post-authentication the nonce is used to query the correct record from which the transaction type field sets the context.</description>
        <inlineHelpText>Post-authentication the nonce is used to query the correct record from which the transaction type field sets the context.</inlineHelpText>
        <label>Transaction Type</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User_Id__c</fullName>
        <label>User Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>userEmail__c</fullName>
        <label>userEmail</label>
        <type>Email</type>
    </fields>
    <label>Company Authorisation</label>
    <nameField>
        <displayFormat>CAUTH{000000}</displayFormat>
        <label>Company Authorisation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Company Authorisations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Transaction__c.object
<CustomObject>
    <fields>
        <fullName>CompanyNumber__c</fullName>
        <label>Company Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Transaction (Company)</relationshipLabel>
        <relationshipName>Transaction_Company</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Form_Name__c</fullName>
        <label>Form Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <label>Transaction Type</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Valid_Step_Ids__c</fullName>
        <description>Pipe delimited list of Step Ids up to the current and next Step only.</description>
        <inlineHelpText>Pipe delimited list of Step Ids up to the current and next Step only.</inlineHelpText>
        <label>Valid Step Ids</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>finishedAttachments__c</fullName>
        <defaultValue>false</defaultValue>
        <label>finishedAttachments</label>
        <type>Checkbox</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>SUB{0000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Transaction_Type__mdt.object
<CustomObject>
    <label>Transaction Type</label>
    <pluralLabel>Transaction Type</pluralLabel>
</CustomObject>

src/objects/Transaction_Type_Step__mdt.object
<CustomObject>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <description>e.g. DS01</description>
        <inlineHelpText>e.g. DS01</inlineHelpText>
        <label>Transaction Type</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Transaction Type Step</label>
    <pluralLabel>Transaction Type Steps</pluralLabel>
</CustomObject>

src/classes/DocStatusControllerTest.cls
@isTest
private class DocStatusControllerTest {

	@isTest static void test_method_one() {

		CompaniesHouseTestData testData = CompaniesHouseTestData.getInstance();

		Transaction_Type__mdt testForm = CompaniesHouseTestData.getInstance().testForm;

		Transaction_Type_Step__mdt testStep1 = CompaniesHouseTestData.getInstance().testStep1;
		Account testPresenter = CompaniesHouseTestData.getInstance().presenterAccount;

		Account testCompany = CompaniesHouseTestData.getInstance().companyAccount;

		// needs mock web callout information here for initialize step test
		insert testPresenter;

		insert testCompany;

		Transaction__c transac = testData.tx;

		transac.Company__c = testCompany.Id;
		transac.Valid_Step_Ids__c = testStep1.Id;
		transac.CompanyNumber__c = '05448736';
		transac.finishedAttachments__c = false;
		transac.Form_Name__c = 'SH19';

		insert transac;


		Blob test2pdfBlob;
		test2pdfBlob = Blob.valueOf('This is a test');
		Attachment testAttachment2 = new Attachment();
		testAttachment2.ParentId = transac.Id;
		testAttachment2.Description = 'Solvency statement';
		testAttachment2.Name = 'Solvency statement' + '.pdf';
		testAttachment2.Body = test2pdfBlob;
		insert testAttachment2;



		Blob testpdfBlob;
		testpdfBlob = Blob.valueOf('This is a test');
		Attachment testAttachment = new Attachment();
		testAttachment.ParentId = transac.Id;
		testAttachment.Description = 'Resolution';
		testAttachment.Name = 'Resolution' + '.pdf';
		testAttachment.Body = testpdfBlob;
		insert testAttachment;
		PageReference documentStatusPage2 = Page.Status;
		documentStatusPage2.getParameters().put('state', 'testNonce2');
		Test.setCurrentPage(documentStatusPage2);
		SecurityManager.createSessionValidityCookie('test@test.com');
		DocStatusController test2controller = new DocStatusController();
		Company_Authorisation__c testAuth = new Company_Authorisation__c();
		testAuth.Company_Access_Token__c = 'test';
		testAuth.Company_Number__c = '9872734234';
		testAuth.userEmail__c = 'test@test.com';
		testAuth.User_Id__c = 'testuserId';
		testAuth.Nonce__c = 'testNonce2';
		testAuth.Transaction_Type__c = 'DS01';
		insert testAuth;

		test2controller.parseQueryString();
		test2controller.findCompanyAuthByNonce();
	}

	@isTest static void test_method_two() {

		CompaniesHouseTestData testData = CompaniesHouseTestData.getInstance();

		Transaction_Type__mdt testForm = CompaniesHouseTestData.getInstance().testForm;

		Transaction_Type_Step__mdt testStep1 = CompaniesHouseTestData.getInstance().testStep1;
		Account testPresenter = CompaniesHouseTestData.getInstance().presenterAccount;

		Account testCompany = CompaniesHouseTestData.getInstance().companyAccount;

		// needs mock web callout information here for initialize step test
		insert testPresenter;

		insert testCompany;

		Transaction__c transac = testData.tx;

		transac.Company__c = testCompany.Id;
		transac.Valid_Step_Ids__c = testStep1.Id;
		transac.CompanyNumber__c = '05448736';
		transac.finishedAttachments__c = false;
		transac.Form_Name__c = 'SH19';

		insert transac;


		Blob test2pdfBlob;
		test2pdfBlob = Blob.valueOf('This is a test');
		Attachment testAttachment2 = new Attachment();
		testAttachment2.ParentId = transac.Id;
		testAttachment2.Description = 'Solvency statement';
		testAttachment2.Name = 'Solvency statement' + '.pdf';
		testAttachment2.Body = test2pdfBlob;
		insert testAttachment2;



		Blob testpdfBlob;
		testpdfBlob = Blob.valueOf('This is a test');
		Attachment testAttachment = new Attachment();
		testAttachment.ParentId = transac.Id;
		testAttachment.Description = 'Resolution';
		testAttachment.Name = 'Resolution' + '.pdf';
		testAttachment.Body = testpdfBlob;
		insert testAttachment;
		PageReference documentStatusPage = Page.Status;
		documentStatusPage.getParameters().put('documentsigningstatus', SecurityManager.encryptText('DS01' + AppConstants.ID_DELIM_CHAR + 'test@email.com' + AppConstants.ID_DELIM_CHAR + transac.id + AppConstants.ID_DELIM_CHAR + '05448736'));
		Test.setCurrentPage(documentStatusPage);
		SecurityManager.createSessionValidityCookie('test@test.com');
		DocStatusController test2controller = new DocStatusController();
		Company_Authorisation__c testAuth = new Company_Authorisation__c();
		testAuth.Company_Access_Token__c = 'test';
		testAuth.Company_Number__c = '9872734234';
		testAuth.userEmail__c = 'test@test.com';
		testAuth.User_Id__c = 'testuserId';
		testAuth.Nonce__c = 'testNonce';
		testAuth.Transaction_Type__c = 'DS01';
		insert testAuth;

		test2controller.initialiseController();
		test2controller.directorName = 'testdirector';
		test2controller.directorSigningStatus = 'signingfinished';
		test2controller.directorDateofBirth = 'Yesterday';
		test2controller.docusignobjectsname = 'docusignObject';
		test2controller.title = 'testtitle';
		test2controller.attachmentId = testAttachment.id;
		test2controller.size = 'testsize';
		test2controller.companytypetext = 'test text';
		test2controller.companyStatus = 'test company status';
		test2controller.companyDateOfCreation = 'companycreationdate yesterday';
		test2controller.showprevious = true;
		test2controller.informationstuff = 'testinformationstuff';

		//test2controller.DestroyCookies();


	}
}