src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CompanyNumber__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Company Number</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/objects/Officer__c.object
<CustomObject>
    <fields>
        <fullName>AuthorizedSigner__c</fullName>
        <label>Authorized Signer</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>IsPresenter__c</fullName>
        <defaultValue>false</defaultValue>
        <label>is Presenter?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>RecipientId__c</fullName>
        <label>Recipient Id</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transaction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Transaction</label>
        <referenceTo>Transaction__c</referenceTo>
        <relationshipLabel>Officers</relationshipLabel>
        <relationshipName>Officers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>isCorporateDirector__c</fullName>
        <defaultValue>false</defaultValue>
        <label>is Corporate Director?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>isDeceased__c</fullName>
        <defaultValue>false</defaultValue>
        <label>is Deceased?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>isPowerOfAttorney__c</fullName>
        <defaultValue>false</defaultValue>
        <label>is Power Of Attorney?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>isSignatory__c</fullName>
        <defaultValue>false</defaultValue>
        <label>is Signatory?</label>
        <type>Checkbox</type>
    </fields>
    <label>Officer</label>
    <nameField>
        <label>Officer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Officers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Presenter__c.object
<CustomObject>
    <description>A person submitting forms to Companies House. May be a company director or an accountant.</description>
    <fields>
        <fullName>Email__c</fullName>
        <inlineHelpText>Email address of the presenter, as given in the user profile from the account.companieshouse.gov.uk API.</inlineHelpText>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <label>Presenter</label>
    <nameField>
        <label>Presenter Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Presenters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Shares__c.object
<CustomObject>
    <description>Share Capital SH19 Dependency</description>
    <fields>
        <fullName>ActiveData__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ActiveData</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Aggregate_nominal_value__c</fullName>
        <label>Aggregate nominal value</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Class_of_Shares__c</fullName>
        <label>Class of Shares</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company_Name__c</fullName>
        <label>Company Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Currency__c</fullName>
        <label>Currency</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Number_of_Shares__c</fullName>
        <label>Number of Shares</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Prescribed_Particulars__c</fullName>
        <label>Prescribed Particulars</label>
        <length>32768</length>
        <type>Html</type>
    </fields>
    <fields>
        <fullName>Total_aggregate_amount_unpaid__c</fullName>
        <label>Total aggregate amount unpaid</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Transaction__c</fullName>
        <label>Transaction</label>
        <referenceTo>Transaction__c</referenceTo>
        <relationshipLabel>Shares</relationshipLabel>
        <relationshipName>Shares</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Share</label>
    <nameField>
        <label>Shares Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Shares</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Transaction__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>CompanyName__c</fullName>
        <label>Company Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CompanyNumber__c</fullName>
        <label>Company Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ContactEmail__c</fullName>
        <description>Presenter Contact information for notifications</description>
        <label>Contact Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>ExpiryDate__c</fullName>
        <description>Date of Expiry calculated from Custom meta data automatically. This is the period between sending a document and the actual signing of the document(s)</description>
        <label>ExpiryDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Expiry_Date_Length__c</fullName>
        <label>Expiry Date Length</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Form_Name__c</fullName>
        <label>Form Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Historical_Valid_Step_Ids__c</fullName>
        <label>Historical Valid Step Ids</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>MultipleDirectors__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If the transaction requires multiple directors</description>
        <label>MultipleDirectors</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PresenterName__c</fullName>
        <label>PresenterName</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>PresenterPhoneNumber__c</fullName>
        <label>PresenterPhoneNumber</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Presenter__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Presenter</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Transaction (Presenter)</relationshipLabel>
        <relationshipName>Transaction_Presented</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RequiredOfficerSign__c</fullName>
        <formula>IF(        isMajorityRequired__c           ,IF(OfficerCount__c &gt; 2, ((IF(MOD(OfficerCount__c,2)=0, OfficerCount__c, OfficerCount__c-1)/2)+1), OfficerCount__c), 1 )</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>RequiredOfficerSign</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Signed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payment pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submission pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Signatures</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Error</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SubmissionId__c</fullName>
        <externalId>true</externalId>
        <label>Submission Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Valid_Step_Ids__c</fullName>
        <description>Pipe delimited list of Step Ids up to the current and next Step only.</description>
        <inlineHelpText>Pipe delimited list of Step Ids up to the current and next Step only.</inlineHelpText>
        <label>Valid Step Ids</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>isLLP__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isLLP</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>isMajorityRequired__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isMajorityRequired?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>sharecurrencyselection__c</fullName>
        <label>sharecurrencyselection</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>SUB{0000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src copy/objects/Transaction__c.object
    <fields>
        <fullName>Warning_Confirmation_Flag__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Warning Confirmation Flag</label>
        <type>Checkbox</type>
    </fields>

src/classes/ShareBuilderController.cls
public with sharing class ShareBuilderController {


    public String transactionSFID {
        get;
        set;
    }
    public String companyName {
        get;
        set;
    }
    public String companyNumber {
        get;
        set;
    }

    public Decimal numberofshares {
        get;
        set;
    }
    public String sharecurrency {
        get;
        set;
    }
    public String classofshares {
        get;
        set;
    }
    public Decimal totalvalueofshares {
        get;
        set;
    }
    public String displayText1 {
        get;
        set;
    }
    public String displayText2 {
        get;
        set;
    }
    public String displayText3 {
        get;
        set;
    }
    public String headerText1 {
        get;
        set;
    }
    public String totalnumberofShares {
        get;
        set;
    }
    public String totalnumberAggregate {
        get;
        set;
    }

    public Boolean addsharedisabled {
        get;
        set;
    }
    public List < Shares__c > shareCapital { get;
        set; }
    public Transaction__c transactionrecords {get; set;}


    SecurityManager securityMgr;
    SubmissionManager submissionMgr;

    public ShareBuilderController() {
        initialize();
    }

    private void initialize() {

        headerText1 = 'Add a Share Capital';
        displayText1 = 'Add Shares';
        //securityMgr = new SecurityManager();
        //submissionMgr = new SubmissionManager();

        String transactionID = 'a0N4E000000mLw8';

        List < Transaction__c > recs = [select Id, Form_Name__c, Presenter__c, ExpiryDate__c, Presenter__r.Name, isMajorityRequired__c, Expiry_Date_Length__c,
            PresenterName__c, PresenterPhoneNumber__c, RequiredOfficerSign__c, ContactEmail__c,
            MultipleDirectors__c, Name, Historical_Valid_Step_Ids__c, CompanyNumber__c,
            Status__c, CompanyName__c, SubmissionId__c, Valid_Step_Ids__c, Warning_Confirmation_Flag__c, Amount__c, isLLP__c,sharecurrencyselection__c,
            (SELECT Id, BodyLength, Name FROM Attachments), (SELECT ActiveData__c, Aggregate_nominal_value__c, Class_of_Shares__c, Company_Name__c, CreatedById, CreatedDate, Currency__c, IsDeleted, Number_of_Shares__c, Prescribed_Particulars__c, Id, Name, Total_aggregate_amount_unpaid__c, Transaction__c FROM Shares__r),
            (Select Id, Name, Email__c, isPresenter__c, isSignatory__c, RecipientId__c,
                AuthorizedSigner__c, isDeceased__c, isPowerOfAttorney__c, isCorporateDirector__c From Officers__r), (SELECT Name, dsfs__DocuSign_Envelope_ID__c, dsfs__Envelope_Link__c, dsfs__Envelope_Status__c, dsfs__Sender__c, dsfs__Sender_Email__c, dsfs__Subject__c FROM DocuSign_Status__r)
            from Transaction__c where Id = : transactionID
        ];

         transactionrecords = recs[0];
        // if (recs.size() == 1) { transactionrecords = recs[0]; }

        shareCapital = transactionrecords.Shares__r;
        transactionSFID = transactionrecords.Id;
        sharecurrency = transactionrecords.sharecurrencyselection__c;
      
        //transactionSFID = paramValue.split(AppConstants.ID_DELIM_SPLIT_CHAR)[0];
        //if (!SubmissionManager.isValidSubmissionId(transactionSFID)) {
        //    return;
        //}
        //        shareCapital = submissionMgr.submission.Shares__r;

        //companyName = paramValue.split(AppConstants.ID_DELIM_SPLIT_CHAR)[1];

        //companyNumber = paramValue.split(AppConstants.ID_DELIM_SPLIT_CHAR)[2];

        return;
    }

    public PageReference viewnewShares() {
        addShare();
        //classofshares, transactionSFID, numberofshares, sharecurrency, classofshares, totalvalueofshares
        return null;
    }

    private void addShare() {
        try {
            //String name, String transactionid, Decimal numberofshares, String sharecurrency, String classofshares, Decimal totalvalueofshares
            insert new Shares__c(Name = classofshares, Transaction__c = transactionrecords.Id, Number_of_Shares__c = numberofshares, Currency__c = sharecurrency, Class_of_Shares__c = classofshares, Total_aggregate_amount_unpaid__c = totalvalueofshares, ActiveData__c = true);

        } catch (DmlException e) {

            ApexPages.Message error = new ApexPages.Message(ApexPages.Severity.ERROR, 'Error: Invalid Input.' + e);
            ApexPages.addMessage(error);
            //return;
        } catch (Exception e) {
            ApexPages.Message error = new ApexPages.Message(ApexPages.Severity.ERROR, 'Error: Invalid Input.' + e);
            ApexPages.addMessage(error);
            //return;

        }

    }
}