src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CompanyNumber__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Company Number</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Transaction__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Transaction</label>
        <referenceTo>Transaction__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
</CustomObject>

src/objects/Transaction__c.object
<CustomObject>
    <fields>
        <fullName>CompanyNumber__c</fullName>
        <label>Company Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Transaction (Company)</relationshipLabel>
        <relationshipName>Transaction_Company</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Form_Name__c</fullName>
        <label>Form Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <label>Transaction Type</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>isDigitalSignatureNeeded__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field show if the form contains a digital signature</description>
        <inlineHelpText>Property checked if the form - transaction need to be signed digitally</inlineHelpText>
        <label>is digital signature needed?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>officerTerminology__c</fullName>
        <label>Officer Terminology</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>SUB{0000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DocusignRecipientStatusDeletionBatchTest.cls
@isTest(seealldata = false)
private class DocusignRecipientStatusDeletionBatchTest {

	@isTest static void testBatch() {
		CompaniesHouseTestData testData = CompaniesHouseTestData.getInstance();		
		Account testCompany = CompaniesHouseTestData.getInstance().companyAccount;

		insert testCompany;

		Transaction__c transac = testData.tx;
		transac.Form_Name__c = 'DS01';
		transac.Transaction_Type__c = 'DS01';
		transac.Company__c = testCompany.Id;
		transac.CompanyNumber__c = '05448736';
		transac.officerTerminology__c = 'test';

		transac.isDigitalSignatureNeeded__c = true;
		insert transac;

		dsfs__DocuSign_Status__c testData3 = new dsfs__DocuSign_Status__c();
		testData3.Transaction__c = transac.Id;
		insert testData3;

		dsfs__DocuSign_Recipient_Status__c testData33 = new dsfs__DocuSign_Recipient_Status__c();
		testData33.dsfs__DocuSign_Recipient_Id__c = 'doawjdoawj';
		testData33.dsfs__Parent_Status_Record__c = testData3.Id;
		insert testData33;


		Contact con1 = CompaniesHouseTestData.getInstance().contact1;

		insert con1;

		dsfs__DocuSign_Recipient_Status__c testData2 = new dsfs__DocuSign_Recipient_Status__c();
		testData2.dsfs__Contact__c = con1.Id;
		testData2.dsfs__Parent_Status_Record__c = testData3.Id;
		testData2.dsfs__DocuSign_Recipient_Id__c = 'ojdojodjdojdoj';
		insert testData2;

		System.assertEquals(2, [Select Id From dsfs__DocuSign_Recipient_Status__c].size());

		Test.startTest();

		Database.executeBatch(new DocusignRecipientStatusDeletionBatch());

		Test.stopTest();

		System.assertEquals(1, [Select Id From dsfs__DocuSign_Recipient_Status__c].size());
	}

}