src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CompanyNumber__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Company Number</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>IsPresenter__c</fullName>
        <formula>if(IsPresenterTEXT__c == &quot;true&quot;,true,false)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>is Presenter? (F)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Middlenames__c</fullName>
        <description>This field describe middlenames of an officer</description>
        <inlineHelpText>Middle names of the officer</inlineHelpText>
        <label>Middlenames</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transaction__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <label>Transaction</label>
        <referenceTo>Transaction__c</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>isSignatoryBehalf__c</fullName>
        <formula>if(isSignatoryBehalfTEXT__c == &quot;true&quot;, true,false)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>is Signatory on behalf? (F)</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>isSignatory__c</fullName>
        <formula>if(isSignatoryTEXT__c == &quot;true&quot;, true, false)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>is Signatory? (F)</label>
        <type>Checkbox</type>
    </fields>
</CustomObject>

src/objects/Officer__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>IsPresenter__c</fullName>
        <defaultValue>false</defaultValue>
        <label>is Presenter?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Transaction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Transaction</label>
        <referenceTo>Transaction__c</referenceTo>
        <relationshipLabel>Officers</relationshipLabel>
        <relationshipName>Officers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>isSignatory__c</fullName>
        <defaultValue>false</defaultValue>
        <label>is Signatory?</label>
        <type>Checkbox</type>
    </fields>
    <label>Officer</label>
    <nameField>
        <label>Officer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Officers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src copy/objects/Officer__c.object
    <fields>
        <fullName>isSignatoryBehalf__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used to mark which officer has been selected by the user.</description>
        <inlineHelpText>DO NOT TOUCH THIS FIELD USED BY BACK END</inlineHelpText>
        <label>is Signatory on behalf?</label>
        <type>Checkbox</type>
    </fields>

src/objects/Transaction__c.object
<CustomObject>
    <fields>
        <fullName>CompanyNumber__c</fullName>
        <label>Company Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Transaction (Company)</relationshipLabel>
        <relationshipName>Transaction_Company</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CreatedDateUnitTest__c</fullName>
        <description>This field is used only for unit testing the TransactionRecordsDeletionBatch</description>
        <inlineHelpText>This field is used only for unit testing the TransactionRecordsDeletionBatch</inlineHelpText>
        <label>CreatedDateUnitTest</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>OfficerCount__c</fullName>
        <label>OfficerCount</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>SoleDirectorPresenter__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used to control the flow if the presenter is a sole director.</description>
        <inlineHelpText>DO NOT TOUCH USED IN THE BACK END</inlineHelpText>
        <label>SoleDirectorPresenter</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <label>Transaction Type</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Valid_Step_Ids__c</fullName>
        <description>Pipe delimited list of Step Ids up to the current and next Step only.</description>
        <inlineHelpText>Pipe delimited list of Step Ids up to the current and next Step only.</inlineHelpText>
        <label>Valid Step Ids</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>finishedAddingShares__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Boolean to set once Shares are finished to bypass the Adding Shares Table and call the next Step</description>
        <label>finishedAddingShares</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>finishedAttachments__c</fullName>
        <defaultValue>false</defaultValue>
        <label>finishedAttachments</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>isBehalfSignatoryEnable__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used to control if we will display the flow of behalf signature selection and input screen</description>
        <inlineHelpText>TO NO TOUCH THIS FIELD BACK END FIELD ONLY</inlineHelpText>
        <label>is behalf signatory enable?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>isDigitalSignatureNeeded__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field show if the form contains a digital signature</description>
        <inlineHelpText>Property checked if the form - transaction need to be signed digitally</inlineHelpText>
        <label>is digital signature needed?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>isMajorityRequired__c</fullName>
        <defaultValue>false</defaultValue>
        <label>isMajorityRequired?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>isPresenterMultipleDirectors__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is used to mark the transaction if the user answer to the question are you a director and if there is more than 1 director</description>
        <inlineHelpText>DO NOT TOUCH THIS FIELD, BACK END ONLY</inlineHelpText>
        <label>is Presenter Multiple Director?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>isSigningFinished__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field shows if the transaction has finished with signing</description>
        <inlineHelpText>If checked then signing process is finished</inlineHelpText>
        <label>is signing finished</label>
        <type>Checkbox</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>SUB{0000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Transaction_Type__mdt.object
<CustomObject>
    <label>Transaction Type</label>
    <pluralLabel>Transaction Type</pluralLabel>
</CustomObject>

src/objects/Transaction_Type_Step__mdt.object
<CustomObject>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <description>e.g. DS01</description>
        <inlineHelpText>e.g. DS01</inlineHelpText>
        <label>Transaction Type</label>
        <length>40</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Transaction Type Step</label>
    <pluralLabel>Transaction Type Steps</pluralLabel>
</CustomObject>

src/classes/TransactionRecordsDeletionBatchTest.cls
/*
Name:  TransactionRecordsDeletionBatchTest.cls
Copyright © 2017  Ribbonfish LTD
======================================================
======================================================
Purpose:
-------

Test class for TransactionRecordsDeletionBatch.cls


======================================================
======================================================
History
------- 
Ver. Author            Date        Detail
1.0  Sylvain Picory    2017-05-26  Initial draft of code.
*/
@isTest
private class TransactionRecordsDeletionBatchTest {
	@isTest static void batchTest() {
        CompaniesHouseTestData testData = CompaniesHouseTestData.getInstance();

        Transaction_Type__mdt testDS01 = CompaniesHouseTestData.getInstance().testDS01;

        Transaction_Type_Step__mdt testStep1 = CompaniesHouseTestData.getInstance().testStep1;
        Account testPresenter = CompaniesHouseTestData.getInstance().presenterAccount;

        Account testCompany = CompaniesHouseTestData.getInstance().companyAccount;

        Contact testContact = CompaniesHouseTestData.getInstance().contact1;
        insert testPresenter;

        insert testCompany;
        Transaction__c transac = testData.tx;
        transac.Transaction_Type__c = 'SH10';
        transac.Company__c = testCompany.Id;
        transac.Valid_Step_Ids__c = testStep1.Id;
        transac.CompanyNumber__c = '05448736';
        transac.finishedAttachments__c = true;
        transac.finishedAddingShares__c = true;
        transac.isDigitalSignatureNeeded__c = true;
        transac.isSigningFinished__c = false;
        transac.SoleDirectorPresenter__c = false;
        transac.isMajorityRequired__c = true;
        transac.isPresenterMultipleDirectors__c = true;
        transac.isBehalfSignatoryEnable__c = true;
        transac.OfficerCount__c = 1;
        transac.CreatedDateUnitTest__c = system.today().addMonths(-13);
        insert transac;

        Attachment testAttachment = new Attachment();
        Blob testpdfBlob;
        testpdfBlob = Blob.valueOf('This is a test');
        testAttachment.parentId = transac.id;
        testAttachment.description = 'testDescription';
        testAttachment.Name = 'SH10';
        testAttachment.body = testpdfBlob;
        insert testAttachment;

        testContact.Transaction__c = transac.id;
        insert testContact;
        Officer__c testoff = new Officer__c();
        testoff.name = 'testfirstname';
        testoff.Surname__c = 'testsurname';
        testoff.Forename__c = 'testforename';
        testoff.Middlenames__c = 'testmiddlename';
        testoff.Email__c = 'testEmail@testemail.com';
        testoff.IsPresenter__c = false;
        testoff.Transaction__c = transac.Id;
        testoff.Contact__c = testContact.id;
        testoff.isSignatoryBehalf__c = true;
        testoff.isSignatory__c = true;
        insert testoff;

        dsfs__DocuSign_Status__c testDoc = new dsfs__DocuSign_Status__c();
        testDoc.Transaction__c = transac.Id;
        insert testDoc;

        Test.startTest();

        Database.executeBatch(new TransactionRecordsDeletionBatch());

        Test.stopTest();

        Decimal count = (Decimal)[Select count(Id) total From Transaction__c ][0].get('total');

        system.assertEquals(0, count);

        count = (Decimal)[Select count(Id) total From dsfs__DocuSign_Status__c ][0].get('total');

        system.assertEquals(0, count);

        count = (Decimal)[Select count(Id) total From Attachment ][0].get('total');

        system.assertEquals(0, count);

        count = (Decimal)[Select count(Id) total From Contact ][0].get('total');

        system.assertEquals(0, count);

        count = (Decimal)[Select count(Id) total From Account ][0].get('total');

        system.assertEquals(0, count);

    }

    @isTest static void batchTest2() {
        RetentionSettings__c testCustomSetting = new RetentionSettings__c();
        testCustomSetting.RetentionPeriodMonths__c = 4;

        insert testCustomSetting;

        CompaniesHouseTestData testData = CompaniesHouseTestData.getInstance();

        Transaction_Type__mdt testDS01 = CompaniesHouseTestData.getInstance().testDS01;

        Transaction_Type_Step__mdt testStep1 = CompaniesHouseTestData.getInstance().testStep1;
        Account testPresenter = CompaniesHouseTestData.getInstance().presenterAccount;

        Account testCompany = CompaniesHouseTestData.getInstance().companyAccount;

        Contact testContact = CompaniesHouseTestData.getInstance().contact1;
        insert testPresenter;

        insert testCompany;
        Transaction__c transac = testData.tx;
        transac.Transaction_Type__c = 'SH10';
        transac.Company__c = testCompany.Id;
        transac.Valid_Step_Ids__c = testStep1.Id;
        transac.CompanyNumber__c = '05448736';
        transac.finishedAttachments__c = true;
        transac.finishedAddingShares__c = true;
        transac.isDigitalSignatureNeeded__c = true;
        transac.isSigningFinished__c = false;
        transac.SoleDirectorPresenter__c = false;
        transac.isMajorityRequired__c = true;
        transac.isPresenterMultipleDirectors__c = true;
        transac.isBehalfSignatoryEnable__c = true;
        transac.OfficerCount__c = 1;
        transac.CreatedDateUnitTest__c = system.today().addMonths(-13);
        insert transac;

        Attachment testAttachment = new Attachment();
        Blob testpdfBlob;
        testpdfBlob = Blob.valueOf('This is a test');
        testAttachment.parentId = transac.id;
        testAttachment.description = 'testDescription';
        testAttachment.Name = 'SH10';
        testAttachment.body = testpdfBlob;
        insert testAttachment;

        testContact.Transaction__c = transac.id;
        insert testContact;
        Officer__c testoff = new Officer__c();
        testoff.name = 'testfirstname';
        testoff.Surname__c = 'testsurname';
        testoff.Forename__c = 'testforename';
        testoff.Middlenames__c = 'testmiddlename';
        testoff.Email__c = 'testEmail@testemail.com';
        testoff.IsPresenter__c = false;
        testoff.Transaction__c = transac.Id;
        testoff.Contact__c = testContact.id;
        testoff.isSignatoryBehalf__c = true;
        testoff.isSignatory__c = true;
        insert testoff;

        dsfs__DocuSign_Status__c testDoc = new dsfs__DocuSign_Status__c();
        testDoc.Transaction__c = transac.Id;
        insert testDoc;

        Test.startTest();

        Database.executeBatch(new TransactionRecordsDeletionBatch());

        Test.stopTest();

        Decimal count = (Decimal)[Select count(Id) total From Transaction__c ][0].get('total');

        system.assertEquals(0, count);

        count = (Decimal)[Select count(Id) total From dsfs__DocuSign_Status__c ][0].get('total');

        system.assertEquals(0, count);

        count = (Decimal)[Select count(Id) total From Attachment ][0].get('total');

        system.assertEquals(0, count);

        count = (Decimal)[Select count(Id) total From Contact ][0].get('total');

        system.assertEquals(0, count);

        count = (Decimal)[Select count(Id) total From Account ][0].get('total');

        system.assertEquals(0, count);

    }

    @isTest static void batchTest3() {
        RetentionSettings__c testCustomSetting = new RetentionSettings__c();
        testCustomSetting.RetentionPeriodMonths__c = 4;

        insert testCustomSetting;
        
        CompaniesHouseTestData testData = CompaniesHouseTestData.getInstance();

        Transaction_Type__mdt testDS01 = CompaniesHouseTestData.getInstance().testDS01;

        Transaction_Type_Step__mdt testStep1 = CompaniesHouseTestData.getInstance().testStep1;
        Account testPresenter = CompaniesHouseTestData.getInstance().presenterAccount;

        Account testCompany = CompaniesHouseTestData.getInstance().companyAccount;

        Contact testContact = CompaniesHouseTestData.getInstance().contact1;
        insert testPresenter;

        insert testCompany;
        Transaction__c transac = testData.tx;
        transac.Transaction_Type__c = 'SH10';
        transac.Company__c = testCompany.Id;
        transac.Valid_Step_Ids__c = testStep1.Id;
        transac.CompanyNumber__c = '05448736';
        transac.finishedAttachments__c = true;
        transac.finishedAddingShares__c = true;
        transac.isDigitalSignatureNeeded__c = true;
        transac.isSigningFinished__c = false;
        transac.SoleDirectorPresenter__c = false;
        transac.isMajorityRequired__c = true;
        transac.isPresenterMultipleDirectors__c = true;
        transac.isBehalfSignatoryEnable__c = true;
        transac.OfficerCount__c = 1;
        transac.CreatedDateUnitTest__c = system.today().addMonths(-2);
        insert transac;

        Attachment testAttachment = new Attachment();
        Blob testpdfBlob;
        testpdfBlob = Blob.valueOf('This is a test');
        testAttachment.parentId = transac.id;
        testAttachment.description = 'testDescription';
        testAttachment.Name = 'SH10';
        testAttachment.body = testpdfBlob;
        insert testAttachment;

        testContact.Transaction__c = transac.id;
        insert testContact;
        Officer__c testoff = new Officer__c();
        testoff.name = 'testfirstname';
        testoff.Surname__c = 'testsurname';
        testoff.Forename__c = 'testforename';
        testoff.Middlenames__c = 'testmiddlename';
        testoff.Email__c = 'testEmail@testemail.com';
        testoff.IsPresenter__c = false;
        testoff.Transaction__c = transac.Id;
        testoff.Contact__c = testContact.id;
        testoff.isSignatoryBehalf__c = true;
        testoff.isSignatory__c = true;
        insert testoff;

        dsfs__DocuSign_Status__c testDoc = new dsfs__DocuSign_Status__c();
        testDoc.Transaction__c = transac.Id;
        insert testDoc;

        Test.startTest();

        Database.executeBatch(new TransactionRecordsDeletionBatch());

        Test.stopTest();

        Decimal count = (Decimal)[Select count(Id) total From Transaction__c ][0].get('total');

        system.assertEquals(1, count);

        count = (Decimal)[Select count(Id) total From dsfs__DocuSign_Status__c ][0].get('total');

        system.assertEquals(1, count);

        count = (Decimal)[Select count(Id) total From Attachment ][0].get('total');

        system.assertEquals(1, count);

        count = (Decimal)[Select count(Id) total From Contact ][0].get('total');

        system.assertEquals(1, count);

        count = (Decimal)[Select count(Id) total From Account ][0].get('total');

        system.assertEquals(1, count);

    }
}