src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>CompanyNumber__c</fullName>
        <caseSensitive>true</caseSensitive>
        <externalId>true</externalId>
        <label>Company Number</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
</CustomObject>

src/objects/Transaction__c.object
<CustomObject>
    <fields>
        <fullName>CompanyNumber__c</fullName>
        <label>Company Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Transaction (Company)</relationshipLabel>
        <relationshipName>Transaction_Company</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Valid_Step_Ids__c</fullName>
        <description>Pipe delimited list of Step Ids up to the current and next Step only.</description>
        <inlineHelpText>Pipe delimited list of Step Ids up to the current and next Step only.</inlineHelpText>
        <label>Valid Step Ids</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>SUB{0000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Transaction_Type__mdt.object
<CustomObject>
    <label>Transaction Type</label>
    <pluralLabel>Transaction Type</pluralLabel>
</CustomObject>

src/objects/Transaction_Type_Step__mdt.object
<CustomObject>
    <label>Transaction Type Step</label>
    <pluralLabel>Transaction Type Steps</pluralLabel>
</CustomObject>

src/classes/CompanyDetailsControllerTest.cls
@isTest
public with sharing class CompanyDetailsControllerTest {

	@isTest static void test_method_one() {
		//CompaniesHouseTestData testData = CompaniesHouseTestData.getInstance();

		//Transaction_Type__mdt testForm = CompaniesHouseTestData.getInstance().testForm;

		//Transaction_Type_Step__mdt testStep1 = CompaniesHouseTestData.getInstance().testStep1;
		//Account testPresenter = CompaniesHouseTestData.getInstance().presenterAccount;

		//Account testCompany = CompaniesHouseTestData.getInstance().companyAccount;

		//// needs mock web callout information here for initialize step test
		//insert testPresenter;

		//insert testCompany;

		//Transaction__c transac = testData.tx;

		//transac.Company__c = testCompany.Id;
		//transac.Valid_Step_Ids__c = testStep1.Id;
		//transac.CompanyNumber__c = '05448736';

		//insert transac;

		//PageReference companydetailstest = Page.Guidance;
		//companydetailstest.getParameters().put('c', SecurityManager.encryptText(transac.Id + AppConstants.ID_DELIM_CHAR + testStep1.Id + AppConstants.ID_DELIM_CHAR + String.valueOf(DateTime.now().getTime())));
		//Test.setCurrentPage(companydetailstest);

		//CompanyDetailsController controller = new CompanyDetailsController();
		//controller.nextAction();
		//controller.previousAction();
	}

	@isTest static void test_method_two() {
		// Implement test code
	}

}