src/objects/Company_Authorisation__c.object
<CustomObject>
    <fields>
        <fullName>Company_Number__c</fullName>
        <label>Company Number</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CreatedDateUnitTest__c</fullName>
        <description>This field is used only for unit testing the CompanyAuthenticationRecordsDeletionBatch</description>
        <inlineHelpText>This field is used only for unit testing the CompanyAuthenticationRecordsDeletionBatch</inlineHelpText>
        <label>CreatedDateUnitTest</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Nonce__c</fullName>
        <label>Nonce</label>
        <length>16</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transaction_Type__c</fullName>
        <description>Post-authentication the nonce is used to query the correct record from which the transaction type field sets the context.</description>
        <inlineHelpText>Post-authentication the nonce is used to query the correct record from which the transaction type field sets the context.</inlineHelpText>
        <label>Transaction Type</label>
        <length>80</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Company Authorisation</label>
    <nameField>
        <displayFormat>CAUTH{000000}</displayFormat>
        <label>Company Authorisation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Company Authorisations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CompanyAuthenticationDeletionBatchTest.cls
@isTest
private class CompanyAuthenticationDeletionBatchTest {
    @isTest static void batchTest() {
        Company_Authorisation__c testRecord = new Company_Authorisation__c();
        testRecord.CreatedDateUnitTest__c = system.today().addDays(-10);
        testRecord.Nonce__c = 'NonceTest';
        testRecord.Transaction_Type__c = 'DS91';
        testRecord.Company_Number__c = '19191919';
        insert testRecord;

        Company_Authorisation__c testRecord2 = new Company_Authorisation__c();
        testRecord2.CreatedDateUnitTest__c = system.today().addDays(-3);
        testRecord2.Company_Number__c = '191919192';
        testRecord2.Transaction_Type__c = 'DS91';
        testRecord2.Nonce__c = 'NonceTest2';
        insert testRecord2;

        Decimal count = (Decimal)[Select count(Id) total From Company_Authorisation__c ][0].get('total');

        system.assertEquals(2, count);

        Test.startTest();

        Database.executeBatch(new CompanyAuthenticationDeletionBatch());

        Test.stopTest();

        count = (Decimal)[Select count(Id) total From Company_Authorisation__c ][0].get('total');

        system.assertEquals(1, count);
    }

}