src/objects/DocuSignSetting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>ab</description>
    <fields>
        <fullName>AccountId__c</fullName>
        <label>Account Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IntegratorKey__c</fullName>
        <label>Integrator Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>URL__c</fullName>
        <label>URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <label>Username</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>DocuSign Setting</label>
</CustomObject>

src/objects/Officer__c.object
<CustomObject>
    <fields>
        <fullName>Transaction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Transaction</label>
        <referenceTo>Transaction__c</referenceTo>
        <relationshipLabel>Officers</relationshipLabel>
        <relationshipName>Officers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Officer</label>
    <nameField>
        <label>Officer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Officers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Transaction__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Signed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payment pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submission pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Signatures</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Error</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>SUB{0000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SendToDocuSignControllerTest.cls
/**
 * Test Class for SendToDocuSignController
 *
 * Unit Test:
 * - SendNowTest: This unit test cover creating and sending envelope, plus getting a token url 
 * to allowed embeded signature
 *
 * To Do: 
 * - unit tests for exceptions
 * 
 * Author: antonio.bravo@golligo.co.uk
 * ab
 **/

@isTest
public class SendToDocuSignControllerTest {

    public static String TOKEN_URL = 'https://demo.docusign.net/Signing/xxxx'; 
	
	//Create Data
    //Create Transaction
	static Transaction__c createTransaction() {
		Transaction__c tx = CompaniesHouseTestData.getInstance().tx;
		tx.Status__c = 'Draft';
		insert tx;
		
		return tx;
	}

	//Create Officer
	static Officer__c createOfficer(Transaction__c tx) {
		Officer__c off = CompaniesHouseTestData.getInstance().off;
		off.Transaction__c = tx.Id;
		insert off;

		return off;
	}

	//Create Custom Setting
    static void createDocuSignSetting() {
    	DocuSignSetting__c dsSett = new DocuSignSetting__c();
    	dsSett.Name = 'Test setting';
    	dsSett.AccountId__c = 'AccountId';
    	dsSett.IntegratorKey__c = 'Key';
    	dsSett.Username__c = 'username';
    	dsSett.Password__c = 'password';
    	dsSett.URL__c = 'DocuSign';

    	insert dsSett;
    }

    @IsTest(SeeAllData=false)
    static void SendNowTest() {

    	//Create Transaction
    	Transaction__c tx = createTransaction();

    	//Create Custom Setting
    	createDocuSignSetting();

    	//create officer
    	Officer__c off = createOfficer(tx);

        test.startTest();

    	//Set Mock WebService Response
        Test.setMock(WebServiceMock.class, new MockWebServiceResponseGenerator());

        //Set Page
        PageReference pageRef = Page.EmbedDocuSign;
        pageRef.getParameters().put('Id', String.valueOf(tx.Id));
        Test.setCurrentPage(pageRef);

        SendToDocuSignController testController = new SendToDocuSignController();
    	testController.embedDocuSignOpen();
    	
    	test.stopTest();

        //Validate
        String tokenURL = testController.tokenURL;
        System.assertEquals(TOKEN_URL, tokenURL);

    }
}