src/objects/DocuSignSetting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <description>ab</description>
    <fields>
        <fullName>AccountId__c</fullName>
        <label>Account Id</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IntegratorKey__c</fullName>
        <label>Integrator Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Password__c</fullName>
        <label>Password</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>RecordIdPrefix__c</fullName>
        <description>This field is to store DocuSign Status Record Id Prefix</description>
        <inlineHelpText>This field is to store DocuSign Status Record Id Prefix</inlineHelpText>
        <label>Record Id Prefix</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>URL__c</fullName>
        <label>URL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Username__c</fullName>
        <label>Username</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>DocuSign Setting</label>
</CustomObject>

src/objects/Officer__c.object
<CustomObject>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Transaction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Transaction</label>
        <referenceTo>Transaction__c</referenceTo>
        <relationshipLabel>Officers</relationshipLabel>
        <relationshipName>Officers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Officer</label>
    <nameField>
        <label>Officer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Officers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Transaction__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Barcode__c</fullName>
        <description>Represents the barcode of the transaction received from CHIPS</description>
        <label>Barcode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CompanyName__c</fullName>
        <label>Company Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CompanyNumber__c</fullName>
        <label>Company Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Form_Name__c</fullName>
        <label>Form Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubmissionId__c</fullName>
        <externalId>true</externalId>
        <label>Submission Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>SUB{0000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/CompaniesHouseTestData.cls
/**
 * Singleton containing various SObjects and Apex class instances suitable for use in test cases.
 * 
 * Getting an instance of this class should *not* do any DML operations, so that we can still call
 * out after getting an instance. If you want stuff on this class persisted, insert it yourself in
 * calling code.
 * 
 * Author: eliot.stock@methodsdigitial.co.uk
 */
public class CompaniesHouseTestData {

    private static CompaniesHouseTestData instance;
    
    public Form ds01 {get; private set;}
    
    public Transaction__c tx {get; private set;}

    public Officer__c off {get; private set;}
    
    public Attachment pdf {get; private set;}

    public dsfs__DocuSign_Status__c dss {get; private set;} //ab
    
    // Prevent construction by making this private. Use getInstance() instead (singleton).  
    private CompaniesHouseTestData() {
        ds01 = new Form('DS01', 1, '08906750', 'Methods Digital Limited');

        Blob b = Crypto.GenerateAESKey(128);
        String h = EncodingUtil.ConvertTohex(b);
        String guid = h.SubString(0,8)+ '-' + h.SubString(8,12) + '-' + h.SubString(12,16) + '-' + h.SubString(16,20) + '-' + h.substring(20);
        
		tx = new Transaction__c(Amount__c = 10, Barcode__c = '12345', CompanyName__c = 'Test Company LTD', CompanyNumber__c = '0987654321', Form_Name__c = 'DS01', SubmissionId__c = guid);

        off = new Officer__c(Name = 'Test Name',
                            Email__c = 'test@test.com');
        
        pdf = new Attachment(Name = 'unit test attachment',
				Body = Blob.valueOf('unit test attachment'),
				ParentId = tx.Id);

        //ab
        dss = new dsfs__DocuSign_Status__c ();
    }

	public static CompaniesHouseTestData getInstance() {
        if (instance == null) {
            instance = new CompaniesHouseTestData();
            createDocuSignSetting();

        }


        return instance;
    }

    //Create Custom Setting
    static void createDocuSignSetting() {
        DocuSignSetting__c dsSett = new DocuSignSetting__c();
        dsSett.Name = 'Test setting';
        dsSett.AccountId__c = 'AccountId';
        dsSett.IntegratorKey__c = 'Key';
        dsSett.Username__c = 'username';
        dsSett.Password__c = 'password';
        dsSett.URL__c = 'DocuSign';

        Schema.DescribeSObjectResult r = dsfs__DocuSign_Status__c.sObjectType.getDescribe();
        String keyPrefix = r.getKeyPrefix();
        dsSett.RecordIdPrefix__c = keyPrefix;

        insert dsSett;
    }
    
}