src/objects/Environment_Variables__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <fields>
        <fullName>Host_Address__c</fullName>
        <label>Host Address</label>
        <type>Url</type>
    </fields>
    <label>Environment_Variables</label>
</CustomObject>

src/objects/Transaction__c.object
<CustomObject>
    <fields>
        <fullName>CompanyName__c</fullName>
        <label>Company Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CompanyNumber__c</fullName>
        <label>Company Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ContactEmail__c</fullName>
        <description>Presenter Contact information for notifications</description>
        <label>Contact Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Form_Name__c</fullName>
        <label>Form Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SignerStatus__c</fullName>
        <label>SignerStatus</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Signed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payment pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submission pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Signatures</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Error</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>SUB{0000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DocStatusUrlTriggerHandler.cls
/**
 * Submission URL
 *
 * Author: leo.bitoy@methods.digital.co.uk
 * 
 *  This trigger handler builds a Document Signing Status URL for the user to track DocuSign Recipient Status view
 *
 *
 *
 *
 **/
public with sharing class DocStatusUrlTriggerHandler {

    private static Environment_Variables__c getSettings() {

        for (Environment_Variables__c s: Environment_Variables__c.getAll().values()) {
            return s;
        }

        System.debug(LoggingLevel.ERROR, 'No active Environment Variables in Custom Settings' + 'Can\'t build the system Host URL.');

        return null;
    }

    public DocStatusUrlTriggerHandler() {
		
	}


    public static void afterUpdateandafterInsert(List < Transaction__c > transactionsList) {

        for (Transaction__c transactionupdater: transactionsList) {
            // list of transactions to update at the end
            if (transactionupdater.Status__c == AppConstants.REQUEST_STATUS_PENDING_SIGNATURES) {
                // loop through transactions from trigger and find the signed status
                Environment_Variables__c settings = getSettings();

                // parameters needed for C value
                String baseURL = settings.Host_Address__c;
                String transactionID = transactionupdater.Id;
                String transactiontype = transactionupdater.Form_Name__c;
                String companyname = transactionupdater.CompanyName__c;
                String contactemail = transactionupdater.ContactEmail__c;
                String companyNumber = transactionupdater.CompanyNumber__c;
                String parametername = baseURL;

                parametername += '/Status?documentsigningstatus=';

                parametername += SecurityManager.encryptText(transactiontype + AppConstants.ID_DELIM_CHAR + contactemail + AppConstants.ID_DELIM_CHAR + transactionID + AppConstants.ID_DELIM_CHAR + companyNumber);

                PageReference downloadreference = new PageReference(parametername);

                System.debug('your signing status url is' + downloadreference);

                transactionupdater.SignerStatus__c = parametername;
            }
        }
    }
}