src/objects/Officer__c.object
<CustomObject>
    <fields>
        <fullName>Transaction__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Transaction</label>
        <referenceTo>Transaction__c</referenceTo>
        <relationshipLabel>Officers</relationshipLabel>
        <relationshipName>Officers</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Officer</label>
    <nameField>
        <label>Officer Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Officers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Transaction__c.object
<CustomObject>
    <fields>
        <fullName>Barcode__c</fullName>
        <description>Represents the barcode of the transaction received from CHIPS</description>
        <label>Barcode</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CompanyName__c</fullName>
        <label>Company Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CompanyNumber__c</fullName>
        <label>Company Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SubmissionId__c</fullName>
        <externalId>true</externalId>
        <label>Submission Id</label>
        <length>255</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Version_Form__c</fullName>
        <description>Represent the version of the form</description>
        <label>Version Form</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>SUB{0000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TransactionSerialiserTest.cls
@isTest
private class TransactionSerialiserTest {

	//Class test to test the convertion of a transaction record into JSON
	@IsTest
	static void test_method_transactionToJSON(){
		CompaniesHouseTestData testData = CompaniesHouseTestData.getInstance();

		Transaction__c transac = testData.tx;

		insert transac;

		Officer__c off = testData.off;

		off.DateSigned__c = system.today();

		off.Transaction__c = transac.Id;

		insert off;

		Officer__c off2 = testData.off2;

		off2.DateSigned__c = system.today();

		off2.Name = 'BLABLA';

		off2.Transaction__c = transac.Id;

		insert off2;

		Attachment att = testData.pdf;
		att.ParentId = transac.Id;

		insert att;

		String resultBody = EncodingUtil.base64Encode(att.Body);

		test.startTest();

		String result = TransactionSerialiser.transactionToJSON(transac);
		throw new Form_CustomException('' + result);

		test.stopTest();

		//Assert
		TransactionSerialiser.metadataWraper mat = (TransactionSerialiser.metadataWraper)JSON.deserialize(result, TransactionSerialiser.metadataWraper.class);
		TransactionSerialiser.formdataWraper form = (TransactionSerialiser.formdataWraper) JSON.deserialize(result, TransactionSerialiser.formdataWraper.class);
		TransactionSerialiser.attachmentsWraper lAtt = (TransactionSerialiser.attachmentsWraper) JSON.deserialize(result, TransactionSerialiser.attachmentsWraper.class);

		//Test metadata
		system.assertEquals(mat.metadata.submissionReference, transac.SubmissionId__c);
		system.assertEquals(mat.metadata.version, transac.Version_Form__c);

		//Test form
		system.assertEquals(form.formdata.filingDetails.barcode, transac.Barcode__c);
		system.assertEquals(form.formdata.filingDetails.receiptDate, system.today().year() + '-' + system.today().month() + '-' + system.today().day());
		system.assertEquals(form.formdata.corporateBody.incorporationNumber ,transac.CompanyNumber__c );
		system.assertEquals(form.formdata.corporateBody.corporateBodyName ,transac.CompanyName__c );

		//Test Attachments
		system.assertEquals(lAtt.attachments.size(), 1);
		system.assertEquals(lAtt.attachments[0].data ,resultBody );


	}
	
}