src/objects/Transaction__c.object
<CustomObject>
    <fields>
        <fullName>AccountNumber__c</fullName>
        <description>This field store the account number if the user pay against an account</description>
        <inlineHelpText>Account number of the user transaction</inlineHelpText>
        <label>Account Number</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>ApplicationBaseURL__c</fullName>
        <label>ApplicationBaseURL</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>ContactEmail__c</fullName>
        <description>Presenter Contact information for notifications</description>
        <label>Contact Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Form_Name__c</fullName>
        <label>Form Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Signed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payment pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submission pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Signatures</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Error</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>isPaymentAccount__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field mark is the transaction will require to load the account through the JSON</description>
        <inlineHelpText>DO NOT TOUCH THIS FIELD USED BY CODE TO CONTROL ACCOUNT PAYMENT</inlineHelpText>
        <label>is paying against an Account?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>isPaymentRequired__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This checkbox is used to acknowledge if a payment is required.</description>
        <inlineHelpText>Populated automatically by code. DO NOT TOUCH</inlineHelpText>
        <label>is payment required?</label>
        <type>Checkbox</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>SUB{0000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

formsenablement/force-app/main/default/classes/TransactionTriggerHandlerTest.cls
@isTest
private class TransactionTriggerHandlerTest {
	
	@isTest static void test_beforeUpdate() {
    CompaniesHouseTestData testData = CompaniesHouseTestData.getInstance();

    Transaction__c transac = testData.tx;
    transac.isPaymentRequired__c = true;
    transac.isPaymentAccount__c = true;
    transac.Form_Name__c = 'DS01';
    transac.Status__c = AppConstants.REQUEST_STATUS_PENDING_SIGNATURES;
    transac.AccountNumber__c = '94948';
    transac.ContactEmail__c = 'test@test.com';
    transac.ApplicationBaseURL__c = 'https://guidedfiling.companieshouse.gov.uk/start?t=DS01';

    Transaction__c tran = transac.clone(true, true, true);
    tran.Status__c = AppConstants.REQUEST_STATUS_SUBMITTED;
    insert tran;
    insert transac;

    List<Transaction__c> lTransac = new List<Transaction__c>();

    lTransac.add(transac);
    lTransac.add(tran);

    TransactionTriggerHandler.beforeUpdate(lTransac);
		// Implement test code


	}
	
}