src/objects/Transaction__c.object
<CustomObject>
    <fields>
        <fullName>ContactEmail__c</fullName>
        <description>Presenter Contact information for notifications</description>
        <label>Contact Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>MultipleDirectors__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If the transaction requires multiple directors</description>
        <label>MultipleDirectors</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ReviewRedirect__c</fullName>
        <description>URL Redirect field to be sent to Presenter once transaction has been set to signed (note this is currently for multiple directors only).
Developer note: This is the encrypted C value parameter to be added as a merged field in the Email correspondence</description>
        <label>ReviewRedirect</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Signed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payment pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submission pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Signatures</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Error</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Valid_Step_Ids__c</fullName>
        <description>Pipe delimited list of Step Ids up to the current and next Step only.</description>
        <inlineHelpText>Pipe delimited list of Step Ids up to the current and next Step only.</inlineHelpText>
        <label>Valid Step Ids</label>
        <length>1000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>SUB{0000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ReviewNotificationTriggerHandler.cls
/**
 * Review Redirect URL for multiple Directors
 *
 * Author: leo.bitoy@methods.digital.co.uk
 * 
 *  This transaction__c review handler trigger builds a review redirect on records with multiple directors
 *
 *
 *
 *
 **/

public class ReviewNotificationTriggerHandler {

     
            // pass transactions to update list to this method from the trigger being called after update/insert
    public static void afterUpdateandafterInsert(List < Transaction__c > transactionsList) {

        List < Transaction__c > transactionsToUpdate = new List < Transaction__c > ();

        List<Transaction__c> transactionListRecords = [Select Id,Valid_Step_Ids__c,Status__c, MultipleDirectors__c From Transaction__c Where Id IN :transactionsList AND Status__c = :AppConstants.REQUEST_STATUS_SIGNED AND MultipleDirectors__c = true];

        for (Transaction__c transactionupdater: transactionListRecords) {
            // list of transactions to update at the end

            // loop through transactions from trigger and find the signed status
            // right now its static
             
                // parameters needed for C value
                String redirectReviewURL = 'https://lbdev2-chformsfactory.cs83.force.com';
                // note need to pull the base sites url either a query or a custom setting.
                String subIDs = transactionupdater.Id;
                String[] stepsId = transactionupdater.Valid_Step_Ids__c.split(AppConstants.ID_DELIM_SPLIT_CHAR);
                String docuSignStepID = stepsId[stepsId.size()-1];

               

                TransactionManager tttt = new TransactionManager((Id)docuSignStepID);

                PageReference pf = tttt.nextStep(subIDs);
                
                redirectReviewURL += pf.getUrl();
                
                System.debug( 'your redirect url is'+ redirectReviewURL);

                transactionupdater.MultipleDirectors__c = false;
                transactionupdater.ReviewRedirect__c = redirectReviewURL; 

                System.debug('These transactions are signed and have multiple directors' + transactionupdater.ContactEmail__c);

                Transaction__c transactionshim = new Transaction__c();
                transactionshim.Id = transactionupdater.Id;
                transactionshim.MultipleDirectors__c = transactionupdater.MultipleDirectors__c;
                transactionshim.ReviewRedirect__c = transactionupdater.ReviewRedirect__c;
                transactionsToUpdate.add(transactionshim);
            

           
        }
        if(!transactionListRecords.isEmpty())
        {

            update transactionsToUpdate;
        }

    }
    
    
}