src/objects/Transaction__c.object
<CustomObject>
    <fields>
        <fullName>MultipleDirectors__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If the transaction requires multiple directors</description>
        <label>MultipleDirectors</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ReviewRedirect__c</fullName>
        <description>URL Redirect field to be sent to Presenter once transaction has been set to signed (note this is currently for multiple directors only).
Developer note: This is the encrypted C value parameter to be added as a merged field in the Email correspondence</description>
        <label>ReviewRedirect</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Signed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payment pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submission pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Signatures</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Error</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>SUB{0000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ReviewNotificationTriggerHandlerTest.cls
@isTest
private class ReviewNotificationTriggerHandlerTest {
	
		// instantiate a new transaction from companies house test data
	static Transaction__c createNewTransaction(){
		Transaction__c newtransaction = CompaniesHouseTestData.getInstance().tx;

		insert newtransaction;
		
		return newtransaction;
	}

	@IsTest(SeeAllData=false)
    static void multidirectorsSigned(){


    	Transaction__c tx = createNewTransaction();

    	// redirect should be the string passed in the trigger and the multi director should be true
    	String redirectURL = 'http://www.google.com';
    	test.startTest();

    	tx.MultipleDirectors__c = true;
		tx.Status__c = AppConstants.REQUEST_STATUS_SIGNED;
		update tx;
    	test.stopTest();

        Transaction__c txAfter = [Select Id, Status__c, ReviewRedirect__c, MultipleDirectors__c from Transaction__c where Id = :tx.Id];
    	
        System.assertEquals(true, txAfter.MultipleDirectors__c);
    	System.assertEquals(AppConstants.REQUEST_STATUS_SIGNED, txAfter.Status__c);
    	System.assertEquals(redirectURL, txAfter.ReviewRedirect__c);

    }	

    @IsTest(SeeAllData=false)
    static void soleDirectorSigned(){
       
        Transaction__c tx = createNewTransaction();

        // redirect should be empty and multi director should be false
        test.startTest();
        tx.MultipleDirectors__c = false;
		tx.Status__c = AppConstants.REQUEST_STATUS_SIGNED;
		update tx;
        test.stopTest();

        String redirectURL = null;
        Transaction__c txAfter = [Select Id, Status__c, ReviewRedirect__c, MultipleDirectors__c  from Transaction__c where Id = :tx.Id];
        
        System.assertEquals(false, txAfter.MultipleDirectors__c);
    	System.assertEquals(AppConstants.REQUEST_STATUS_SIGNED, txAfter.Status__c);
    	System.assertEquals(redirectURL, txAfter.ReviewRedirect__c);
    }

    @IsTest(SeeAllData=false)
    static void multidirectorUnsigned(){

        Transaction__c tx = createNewTransaction();

    	// redirect should be empty

    	test.startTest();
    	tx.MultipleDirectors__c = true;
		tx.Status__c = AppConstants.REQUEST_STATUS_DRAFT;
		update tx;
    	test.stopTest();
    	
    	String redirectURL = null;

        Transaction__c txAfter = [Select Id, Status__c, ReviewRedirect__c, MultipleDirectors__c  from Transaction__c where Id = :tx.Id];
    	
        System.assertEquals(true, txAfter.MultipleDirectors__c);
    	System.assertEquals(AppConstants.REQUEST_STATUS_DRAFT, txAfter.Status__c);
    	System.assertEquals(redirectURL, txAfter.ReviewRedirect__c);

    }

	
}