src/objects/Transaction__c.object
<CustomObject>
    <fields>
        <fullName>Form_Name__c</fullName>
        <label>Form Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Signed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payment pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submission pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Signatures</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Error</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>SUB{0000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/AttachmentTriggerHandlerTest.cls
/**
 * Test Class for AttachmentTriggerHandler
 *
 * Unit Test:
 * - Update ParentID when Prefix Name is ATTPREFIXNAME
 * - Do not update when Prefix Name is different from ATTPREFIXNAME
 * 
 * Author: antonio.bravo@golligo.co.uk
 * ab
 **/
@isTest
public class AttachmentTriggerHandlerTest {
    
    //Create Data
	static Transaction__c createTransaction(){
		Transaction__c tx = CompaniesHouseTestData.getInstance().tx;
		tx.Status__c = 'Draft';
        tx.Form_Name__c = 'DS01 Test';
		insert tx;
		
		return tx;
	}

	static dsfs__DocuSign_Status__c createDocSignStatus(Transaction__c tx){
		dsfs__DocuSign_Status__c dss = CompaniesHouseTestData.getInstance().dss;
		dss.Transaction__c = tx.Id;
		insert dss;

		return dss;
	}



    @IsTest(SeeAllData=false)
    static void updateRelatedTo(){

    	//Create Transaction record
    	Transaction__c tx = createTransaction();

    	//Create DocuSign Status record
    	dsfs__DocuSign_Status__c dss = createDocSignStatus(tx);

    	
    	test.startTest();
        
        Attachment att = CompaniesHouseTestData.getInstance().pdf;
        att.Name = 'DS01 Test';
        att.ParentId = dss.Id;
        insert att;
    	
    	test.stopTest();

        //Validate
        Attachment attAfter = [Select Id, ParentId from Attachment where ParentId = :tx.Id];
        System.assertEquals(tx.Id, attAfter.ParentId);
    }

    @IsTest(SeeAllData=false)
    static void doNotUpdateRelatedTo(){
        // Attachment with prefix Name different from ATTNAMEPREFIX should not update ParentId
        // e.g. DocuSign is creating Certificates. This attachments should stay related to DocuSign Status record


        //Create Transaction record
    	Transaction__c tx = createTransaction();

    	//Create DocuSign Status record
    	dsfs__DocuSign_Status__c dss = createDocSignStatus(tx);

    	    	
    	test.startTest();
        
        Attachment att = CompaniesHouseTestData.getInstance().pdf;
        att.Name = 'Certificate'; 
        att.ParentId = dss.Id;
        insert att;
    	
    	test.stopTest();

        //Validate
        Attachment attAfter = [Select Id, ParentId from Attachment where ParentId = :dss.Id];
        System.assertEquals(dss.Id, attAfter.ParentId);
    }
}