src/objects/Transaction__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Signed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payment pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submission pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Signatures</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Error</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>SUB{0000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DeleteTransactionButton.cls
/*
Name:  DeleteTransactionButton.cls
Copyright © 2017  Ribbonfish LTD
======================================================
======================================================
Purpose:
-------

This button will be used to delete the transaction with the related officer
======================================================
======================================================
History
------- 
Ver. Author            Date        Detail
1.0  Sylvain Picory    2017-05-26  Initial draft of code.
*/
public with sharing class DeleteTransactionButton {

	private ApexPages.StandardController standardController;

	public DeleteTransactionButton(ApexPages.StandardController stdController) {
		this.standardController = stdController;
	}

	public Pagereference initButton()
	{
		Id profileID = UserInfo.getProfileId();

		Profile prof = [Select Id, Name From Profile where Id = :profileID];
		
		Id transactionID = standardController.getId();

		if(!prof.Name.equals('System Administrator'))
			return new Pagereference('/' );		

		Transaction__c tTemp = new Transaction__c();
		tTemp.Id = transactionID;
		tTemp.Status__c = 'deleteContact';

		update tTemp;

		delete tTemp;

		return new Pagereference('/' );		
	}	
}