src/objects/Transaction__c.object
<CustomObject>
    <fields>
        <fullName>Company__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Company</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Transaction (Company)</relationshipLabel>
        <relationshipName>Transaction_Company</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>CreatedDateUnitTest__c</fullName>
        <description>This field is used only for unit testing the TransactionRecordsDeletionBatch</description>
        <inlineHelpText>This field is used only for unit testing the TransactionRecordsDeletionBatch</inlineHelpText>
        <label>CreatedDateUnitTest</label>
        <type>DateTime</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>SUB{0000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/BusinessAccountRecordsDeletionBatch.cls
public with sharing class BusinessAccountRecordsDeletionBatch implements Database.Batchable<sObject> {
	public BusinessAccountRecordsDeletionBatch() {
		
	}

    String query;
    
    public Database.QueryLocator start(Database.BatchableContext BC) {
               
        query = 'SELECT Id, isPersonAccount from Account where isPersonAccount = false And Id Not IN (Select Company__c from Transaction__c) And';

        String whereCondition = ' CreatedDate != TODAY';

        if(Test.isRunningTest())
        {
            whereCondition = ' CreatedDateUnitTest__c != TODAY';
        }

        query += whereCondition;

        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext BC, List<sObject> scope) {
        //delete the scope result

        if(!scope.isEmpty())
            delete scope;
    }
    
    public void finish(Database.BatchableContext BC) {
        //Run other batch in the finish
    }
}