src/objects/Transaction__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Signed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payment pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submission pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Signatures</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Error</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>SUB{0000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DocuSignStatusTriggerHandler.cls
/**
 * DocuSign Status Trigger Handler
 * Update Transaction Status to completed when Envelope is completed
 *
 * Author: antonio.bravo@golligo.co.uk
 * ab
 **/
public class DocuSignStatusTriggerHandler{
    public static final String DRAFTSTATUS = 'Draft';
    public static final String SIGNEDSTATUS = 'Signed';
    public static final String COMPLETEDSTATUS = 'Completed';

    public static void beforeUpdate(List<dsfs__DocuSign_Status__c> newList){
        
        Set<Id> txIds = new Set<Id>();
        List<Transaction__c> transactionToUpdate = new List<Transaction__c>();

    
        for(dsfs__DocuSign_Status__c dss : newList){
            if(dss.dsfs__Envelope_Status__c == COMPLETEDSTATUS)
                txIds.add(dss.Transaction__c);
        }

        //Update Transactions on DRAFTSTATUS
        for(Transaction__c tx : [Select Id, Status__c from Transaction__c where Id IN :txIds]) {
            if(tx.Status__c == DRAFTSTATUS){
                tx.Status__c = SIGNEDSTATUS;
                transactionToUpdate.add(tx);
            }
        }
         
        //Update Transactions
        if(!transactionToUpdate.isEmpty())
            update transactionToUpdate;

    }
}