src/objects/Transaction__c.object
<CustomObject>
    <fields>
        <fullName>CompanyName__c</fullName>
        <label>Company Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CompanyNumber__c</fullName>
        <label>Company Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Draft</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Signed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Payment pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Paid</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submission pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Submitted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Accepted</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Declined</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending Signatures</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Error</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>SUB{0000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OfficersQueryAction_Test.cls
/**
 * Test Class for OfficersQueryAction
 *
 * Unit Test:
 * - no active Director Officers
 *
 * To Do: Update mock to return a company with multiple active Directors.
 * 
 * Author: antonio.bravo@golligo.co.uk
 * ab
 **/
@isTest(SeeAllData=false)
public class OfficersQueryAction_Test {

	public static testMethod void getOfficers_Test() {
		List<String> inputList = new List<String>();
		List<String> returnList;

		Transaction__c trans = createTransaction();

		Test.startTest();
		inputList.add(trans.Id);
        Test.setMock(HttpCalloutMock.class, new ChApiMock());

		returnList = OfficersQueryAction.getOfficers(inputList);

		System.assertEquals(1, returnList.size()); 
		System.assertEquals('', returnList.get(0)); //mock generator is returning 0 current Officers
		System.debug(returnList);
		Test.stopTest();
	}

	public static testMethod void getOfficersByCompanyNumber_Test() {
		String companyNumber = '00000000';

		String officerList = ChApiMock.OFFICERS_LIST;

		//Initialise the data
		CompaniesHouseCalloutsResponse resp = new CompaniesHouseCalloutsResponse();
		List<CompaniesHouse.OfficerDetails> directorDetailsListExpected = resp.getResponseOfficerList(officerList).items;

		Test.startTest();
		
        Test.setMock(HttpCalloutMock.class, new ChApiMock());

		List<CompaniesHouse.OfficerDetails> directorDetailsList = OfficersQueryAction.getOfficers(companyNumber);
		System.assertEquals(1, directorDetailsList.size()); 
		System.assertEquals(directorDetailsListExpected + '' , directorDetailsList + ''); //We use dynamic casting 
		Test.stopTest();
	}

	/**************** Aux ****************/
	private static Transaction__c createTransaction() {
		Transaction__c trans = new Transaction__c();
		trans.CompanyName__c = 'Test Company';
		trans.CompanyNumber__c = '00000000';
		trans.Status__c = 'Draft';
		insert trans;

		return trans;
	}
}