src/objects/Transaction__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>SUB{0000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SmartPayUrlTest.cls
/**
 * Author: eliot.stock@methods.digital.co.uk.
 */
@isTest
public class SmartPayUrlTest {
    
    @isTest
    public static void canBuildUrl() {
        Test.startTest();
        
        Transaction__c tx = new Transaction__c(Amount__c  = 10.0);
        insert tx;
        
        // Going for coverage only until BETA, since all this could change.
        SmartPayUrl url = new SmartPayUrl.Builder()
            	.merchantReference(tx.Id)
            	.paymentAmount(tx.Amount__c)
            	.build();
        String redirectUrl = url.toString();
        
        Test.stopTest();
    }

}