src/objects/Transaction__c.object
<CustomObject>
    <fields>
        <fullName>ExpirySEnt__c</fullName>
        <defaultValue>false</defaultValue>
        <description>expiry email sent and okay to set to inactive and/or delete file</description>
        <label>ExpirySEnt</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>InActiveTransaction__c</fullName>
        <defaultValue>false</defaultValue>
        <label>InActiveTransaction</label>
        <type>Checkbox</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>SUB{0000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TransactionCleanup.cls
/*
Name:  transactionCleanup.cls
Copyright © 2016  Methods Digital
======================================================
======================================================
Purpose:
-------

Cleanups up expired transactions after Expiry email has been sent.
Note: Transaction is not deleted but rather set as inactive

======================================================
======================================================
History
------- 
Ver. Author        Date        Detail
1.0  Leo Bitoy&    2016-10-05  Initial development.
*/

global class TransactionCleanup implements Database.Batchable < sObject > {

    String query = 'SELECT Id,Name, ExpirySEnt__c, InActiveTransaction__c FROM Transaction__C WHERE ExpirySEnt__c = True';


    global TransactionCleanup() {

    }

    global Database.QueryLocator start(Database.BatchableContext BC) {
        return Database.getQueryLocator(query);
    }

    global void execute(Database.BatchableContext BC, List < Transaction__c > scope) {
        for (Transaction__c a: scope) {
            a.InActiveTransaction__c = true;
        }
        update scope;
    }

    global void finish(Database.BatchableContext BC) {}


}