src/objects/User_Authorisation__c.object
<CustomObject>
    <fields>
        <fullName>CreatedDateUnitTest__c</fullName>
        <description>This field is used only for unit testing the UserAuthenticationRecordsDeletionBatch</description>
        <inlineHelpText>This field is used only for unit testing the UserAuthenticationRecordsDeletionBatch</inlineHelpText>
        <label>CreatedDateUnitTest</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Nonce__c</fullName>
        <label>Nonce</label>
        <length>16</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>User Authorisation</label>
    <nameField>
        <displayFormat>UAUTH{000000}</displayFormat>
        <label>User Authorisation Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>User Authorisations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/UserAuthenticationDeletionBatchTest.cls
@isTest
private class UserAuthenticationDeletionBatchTest {
    @isTest static void batchTest() {
        User_Authorisation__c testRecord = new User_Authorisation__c();
        testRecord.CreatedDateUnitTest__c = system.today().addDays(-10);
        testRecord.Nonce__c = 'NonceTest';
        insert testRecord;

        User_Authorisation__c testRecord2 = new User_Authorisation__c();
        testRecord2.CreatedDateUnitTest__c = system.today().addDays(-3);
        testRecord2.Nonce__c = 'NonceTest2';
        insert testRecord2;

        Decimal count = (Decimal)[Select count(Id) total From User_Authorisation__c ][0].get('total');

        system.assertEquals(2, count);

        Test.startTest();

        Database.executeBatch(new UserAuthenticationDeletionBatch());

        Test.stopTest();

        count = (Decimal)[Select count(Id) total From User_Authorisation__c ][0].get('total');

        system.assertEquals(1, count);
    }
  
}